apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-supervisor
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xinference-supervisor
    {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: xinference-supervisor
      {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.xinferenceSupervisor.supervisor.args | nindent 8 }}
        command:
        - xinference-supervisor
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: XINFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.common.xinference_image | quote }}
        name: supervisor
        ports: {{- toYaml .Values.xinferenceSupervisor.supervisor.ports | nindent 10 }}
        resources: {{- toYaml .Values.xinferenceSupervisor.supervisor.resources | nindent 10 }}
        volumeMounts: {{- toYaml .Values.xinferenceSupervisor.supervisor.volumeMounts | nindent 10 }}
      volumes: {{- toYaml .Values.xinferenceSupervisor.volumes | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-supervisor
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceSupervisor.type }}
  selector:
    app: xinference-supervisor
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceSupervisor.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWeb.type }}
  selector:
    app: xinference-supervisor
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceWeb.ports | toYaml | nindent 2 }}