name: Release Charts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get app version
        shell: bash
        run: |
          if [[ "$GITHUB_REF" =~ ^"refs/tags/" ]]; then
            export GIT_TAG=$(echo "$GITHUB_REF" | sed -e "s/refs\/tags\///g")
          fi
          
          if [[ -n "$GIT_TAG" ]]; then
            APP_VERSION="$GIT_TAG"
          else
            APP_VERSION=$(git rev-parse --abbrev-ref HEAD)
          fi
          
          echo "Will handle branch/tag $APP_VERSION"
          echo "XINFERENCE_APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Helm package with app version
        shell: bash
        run: |
          cd charts/xinference
          helm package ./ --app-version $XINFERENCE_APP_VERSION --destination ../../.cr-release-packages/
          cd ../..

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        with:
          skip_packaging: "yes"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
